server:
  port: 8761

spring:
  application:
    name: cloud-eureka
  security:
    basic:
      enabled: false
    user:
      name: test
      password: 123456


eureka:
  instance:
      hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000

